[build]
  # SvelteKit build command
  command = "npm run build"
  
  # SvelteKit build output directory
  publish = "build"

[build.environment]
  # Node version for SvelteKit
  NODE_VERSION = "18"

# SvelteKit handles routing internally, no redirects needed
# The adapter-netlify automatically configures this

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://kit.fontawesome.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com https://use.fontawesome.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com https://use.fontawesome.com https://ka-f.fontawesome.com; img-src 'self' data: https:; connect-src 'self'"

# Cache static assets
[[headers]]
  for = "/_app/immutable/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
